receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800


exporters:
  debug:
    verbosity: detailed

  zipkin:
    endpoint: http://jaeger:9411/api/v2/spans

  elasticsearch:
    endpoints: [ "http://elasticsearch:9200" ]
    index: logs
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"
    enable_open_metrics: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [elasticsearch]