receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:


exporters:
  debug:
    verbosity: detailed

  zipkin:
    endpoint: http://jaeger:9411/api/v2/spans

  elasticsearch:
    endpoints: [ "http://elasticsearch:9200" ]
    index: logs
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9464"
    enable_open_metrics: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin,debug]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]