version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # OTLP gRPC receiver
      - "9411:9411"    # Zipkin endpoint (otel-collector orqali trace yuborish uchun)
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:16686" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "4317:4317"  # OpenTelemetry gRPC receiver
      - "4318:4318"  # OpenTelemetry HTTP receiver
      - "9464:9464"  # OpenTelemetry Prometheus Exporter
      - "8889:8889"
    depends_on:
      - jaeger
      - elasticsearch
    networks:
      - otel-collector

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=otlp-write-receiver'
    ports:
      - "9090:9090"
    networks:
      - otel-collector

#  alertmanager:
#    image: prom/alertmanager
#    container_name: alertmanager
#    volumes:
#      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
#    command:
#      - --config.file=/etc/alertmanager/alertmanager.yml
#    ports:
#      - "9093:9093"
#    networks:
#      - otel-collector  # ✅ Attach to shared network


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - elasticsearch
    networks:
      - otel-collector

volumes:
  esdata:
  grafana-storage:


networks:
  otel-collector:  # 🚀 Using the shared network
    external: true