groups:
  - name: http-5xx-alerts
    rules:
      - alert: HighHttp5xxErrorRate
        expr: rate(http_server_requests_milliseconds_bucket{status=~"5.."}[30s]) > 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "HTTP 5xx error detected in {{ $labels.job }}  {{ $labels.error }} {{ $labels.uri }} "
          description: "At least one 5xx response was returned by {{ $labels.job }} in the last 30 seconds."
